//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////以下代码为自动生成，请勿手工改动//////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
class OprateResult
	{
		// 操作类型
		public static OPRATE_TYPE_LOGIN			:number = 1;	// 登录
		public static OPRATE_TYPE_KICKING			:number = 2;	// 踢人
		public static OPRATE_TYPE_JUMP			:number = 3;	// 跳
		public static OPRATE_TYPE_ATTK_LOSE			:number = 4;	// 攻击失败
		public static OPRATE_TYPE_SPELL_LOSE			:number = 5;	// 技能释放失败
		public static OPRATE_TYPE_INTERACTION			:number = 6;	// 交互,如使用GAMEOBJ 与NPC对话，交接任务等
		public static OPRATE_TYPE_USE_GAMEOBJECT			:number = 7;	// 使用游戏对象
		public static OPRATE_TYPE_BAG			:number = 8;	// 包裹
		public static OPRATE_TYPE_TRADE			:number = 9;	// 交易
		public static OPRATE_TYPE_CHAT			:number = 10;	// 聊天
		public static OPERTE_TYPE_RECEIVE_GIFT_PACKS			:number = 11;	// 领取补偿礼包
		public static OPERTE_TYPE_QUEST			:number = 12;	// 任务
		public static OPERTE_TYPE_NPCBUY			:number = 13;	// 购买商品
		public static OPERTE_TYPE_FUBEN			:number = 14;	// 副本
		public static OPERTE_TYPE_KUAFU			:number = 15;	// 跨服
		public static OPERTE_TYPE_RANK_LIST			:number = 16;	// 排行榜
		public static OPERTE_TYPE_CLOSE			:number = 17;	// 连接关闭
		public static OPERTE_TYPE_HOSTING			:number = 18;	// 托管
		public static OPERTE_TYPE_STRENGTH			:number = 19;	// 强化
		public static OPERTE_TYPE_CHANGE_BATTLE_MODE_LOSE			:number = 20;	// 切换战斗模式失败
		public static OPERTE_TYPE_SOCIAL			:number = 21;	// 社交
		public static OPERTE_TYPE_FACTION			:number = 22;	// 帮派
		public static OPERTE_TYPE_FIELD_BOSS			:number = 23;	// 野外BOSS
		public static OPERTE_TYPE_WORLD_BOSS			:number = 24;	// 世界BOSS
		public static OPRATE_TYPE_MOUNT_QICHENG			:number = 25;	// 坐骑骑乘
		public static OPRATE_TYPE_TELEPORT			:number = 26;	// 传送
		public static OPRATE_TYPE_UPGRADE			:number = 27;	// 游戏中的升级操作
		public static OPRATE_TYPE_ACTIVITY			:number = 28;	// 活动
		public static OPRATE_TYPE_ACHIEVE			:number = 29;	// 成就
		public static OPRATE_TYPE_ATHLETICS			:number = 30;	// 竞技
		public static OPRATE_TYPE_XIANFU			:number = 31;	// 仙府夺宝
		public static OPRATE_TYPE_REWARD			:number = 32;	// 获得物品
		public static OPRATE_TYPE_DOUJIAN			:number = 33;	// 斗剑台
		public static OPRATE_TYPE_GEM			:number = 34;	// 宝石
		public static OPRATE_TYPE_MONEYTREE			:number = 35;	// 摇钱树
		public static OPRATE_TYPE_NEED_NOTICE			:number = 36;	// 需要跑马灯
		public static OPRATE_TYPE_GROUP			:number = 37;	// 组队相关的
		public static OPRATE_TYPE_GIFTCODE			:number = 38;	// 兑换码相关的
		// 登录相关操作返回
		public static OPRATE_RESULT_SUCCESS			:number = 1;	// 成功
		public static OPRATE_RESULT_NAME_REPEAT			:number = 2;	// 名称重复
		public static OPRATE_RESULT_NAME_ILLEGAL			:number = 3;	// 名称非法
		public static OPRATE_RESULT_CHAR_CAP			:number = 4;	// 角色数量达到上限
		public static OPRATE_RESULT_SCENED_CLOSE			:number = 5;	// 场景服未开启
		public static OPRATE_RESULT_SCENED_ERROR			:number = 6;	// 场景服重置，其实就是崩了一个场景服换一个新的
		public static OPRATE_RESULT_LOGINED_IN			:number = 7;	// 角色已登录
		public static OPRATE_RESULT_OTHER_LOGINED			:number = 8;	// 角色其他地方登录
		public static OPRATE_RESULT_GAME_VERSION_ERROR			:number = 9;	// 游戏版本不对
		public static OPRATE_RESULT_MAP_VERSION_ERROR			:number = 10;	// 地图素材版本不对
		public static OPRATE_RESULT_DATA_VERSION_ERROR			:number = 11;	// data素材版本不对
		public static OPRATE_RESULT_VERSION_FORMAT_ERROR			:number = 12;	// 客户端发来的版本信息格式不对
		public static OPRATE_RESULT_APPD_ERROR			:number = 13;	// 应用服异常重启
		public static OPRATE_RESULT_LOCK_ACCOUNT			:number = 14;	// 帐号被封
		public static OPRATE_RESULT_LOCK_IP			:number = 15;	// IP被封
		public static OPRATE_RESULT_APPD_CLOSE			:number = 16;	// 应用服未开启
		public static OPRATE_RESULT_NAME_TOO_LONG			:number = 17;	// 名字太长
		public static OPRATE_RESULT_NAME_HAS_PINGBI			:number = 18;	// 有屏蔽词
		public static OPRATE_RESULT_LOGOUT_UNFINISHED			:number = 19;	// 该角色上一次的登出未完成，请等待
		public static OPRATE_RESULT_PID_OR_SID_ERROR			:number = 20;	// 服务器id或者平台id错误
		public static OPRATE_RESULT_DB_RESULT_ERROR			:number = 21;	// 数据库查询出问题了
		public static OPRATE_RESULT_MERGE_SERVER			:number = 22;	// 合服了
		public static OPRATE_RESULT_PLAYER_ZIBAO			:number = 23;	// 自爆
		public static OPRATE_RESULT_GENDER_ILLEGAL			:number = 24;	// 角色种类异常
		// 系统踢人的原因
		public static KICKING_TYPE_GM_LOCK_IP			:number = 0;	// 封IP
		public static KICKING_TYPE_GM_LOCK_ACCOUNT			:number = 1;	// 封号
		public static KICKING_TYPE_GM_KICKING			:number = 2;	// 从GM表中读取的踢人
		public static KICKING_TYPE_KUANGCHANG_RELIVE			:number = 3;	// 荒芜矿场非法复活
		public static KICKING_TYPE_FUCK_PINGBI			:number = 4;	// 聊天点带屏蔽词
		public static KICKING_TYPE_QUEST_GET_ITEM			:number = 5;	// 刷物品
		public static KICKING_TYPE_NOT_MONEY			:number = 6;	// 钱负数还继续消费
		// 跳跃操作返回
		public static JUMP_RESULT_NOMAL			:number = 1;	// 无，默认结果
		public static JUMP_RESULT_DEAD			:number = 2;	// 死了你还跳，果断是诈尸
		public static JUMP_RESULT_ENERGY			:number = 3;	// 体力不足
		public static JUMP_RESULT_MAP_CANT_JUMP			:number = 4;	// 地图无法跳跃
		public static JUMP_RESULT_CANT_JUMP			:number = 5;	// 玩家被限制不能跳跃
		public static JUMP_RESULT_MAX_DISTANCE			:number = 6;	// 超过最大距离
		public static JUMP_RESULT_WRONG_COORD			:number = 7;	// 无效坐标，障碍点之流
		public static JUMP_RESULT_SPELL_CD			:number = 8;	// 跳跃技能cd中
		public static JUMP_RESULT_NOT_ACTIVE_SPELL			:number = 9;	// 2段跳没有激活
		// 攻击操作返回
		public static ATTACK_LOST_CANTATTACK			:number = 1;	// 被限制不能攻击
		public static ATTACK_LOST_TARGET_DEAD			:number = 2;	// 目标已经死亡
		public static ATTACK_LOST_NEED_TARGET			:number = 3;	// 攻击需要一个目标
		public static ATTACK_LOST_OUT_OF_RANGE			:number = 4;	// 超出攻击范围
		public static ATTACK_LOST_WRONG_TARGET			:number = 5;	// 错误的目标
		public static ATTACK_LOST_MOVING			:number = 6;	// 正在移动状态下不能攻击
		// 技能释放操作返回
		public static LOST_RESON_SPELL_DOENT_EXIST			:number = 1;	// 技能不存在
		public static LOST_RESON_NOT_HAVE_SPELL			:number = 2;	// 你没有这个技能
		public static LOST_RESON_NOT_ENOUGH_ANGER			:number = 3;	// 怒气值不足
		public static LOST_RESON_SPELL_COOLDOWN			:number = 4;	// 冷却
		public static LOST_RESON_ALREADY_CAST			:number = 5;	// 已经在施法
		public static LOST_RESON_TARGET_DEAD			:number = 6;	// 目标已经死亡
		public static LOST_RESON_NEED_TARGET			:number = 7;	// 此技能需要一个目标
		public static LOST_RESON_JUMP_DENY			:number = 8;	// 跳跃状态不能施法
		public static LOST_RESON_SCENE_DENY			:number = 9;	// 场景禁止施法
		public static LOST_RESON_CAN_NOT_CAST			:number = 10;	// 无法施法
		public static LOST_RESON_HAS_CONFLICT_SPELL			:number = 11;	// 有技能冲突
		public static LOST_RESON_NOTHAS_CHUZHAN			:number = 12;	// 当前没有出战兵种
		public static LOST_RESON_WRONG_FACTION			:number = 13;	// 同一阵营不能攻击（争霸天下用）
		public static LOST_RESON_ACTIVE_SPELL_SUCCESS			:number = 14;	// 技能激活成功
		public static LOST_RESON_IN_SAFE_ZONE			:number = 15;	// 安全区域不能攻击（大沼泽用）
		public static LOST_RESON_YXT_WRONG_FACTION			:number = 16;	// 同一阵营不能攻击（英雄帖用）
		public static LOST_RESON_PVP_STATE			:number = 17;	// PVP状态不能释放
		// 交互操作返回
		public static INTERACTION_TOO_FAR			:number = 1;	// NPC太远
		public static INTERACTION_BOOK_DAILYNUM_FULL			:number = 2;	// 奇遇日常任务次数已满
		public static INTERACTION_NO_ENOUGH_ENDURANCE			:number = 3;	// 精力值不够
		public static INTERACTION_JHM_ERROR			:number = 4;	// 激活码错误
		public static INTERACTION_WORSHIP			:number = 5;	// 城主膜拜
		public static INTERACTION_JHM_HAVE			:number = 6;	// 激活码奖励已领取
		public static INTERACTION_JHM_IS_USED			:number = 7;	// 激活码已使用
		public static INTERACTION_JHM_NOT_USE_RANGE			:number = 8;	// 不在使用范围内
		// 使用游戏对象操作返回
		public static USE_GAMEOBJECT_SUCCEED			:number = 1;	// 使用游戏对象成功
		public static USE_GAMEOBJECT_FAIL			:number = 2;	// 使用游戏对象失败
		public static USE_GAMEOBJECT_QUEST			:number = 3;	// 采集成功
		public static USE_GAMEOBJECT_TOO_FAST			:number = 4;	// 采集速度太快
		// 包裹操作返回
		public static BAG_RESULT_NULL			:number = 1;	// 路过的
		public static BAG_RESULT_ITEM_NOT_EXIST			:number = 2;	// 物品不存在
		public static BAG_RESULT_CHANGE_ERROR			:number = 3;	// 交换位置错误
		public static BAG_RESULT_DESTROY_BIND			:number = 4;	// 删除绑定的
		public static BAG_RESULT_ITEM_NOT_SELF			:number = 5;	// 不是自己的物品
		public static BAG_RESULT_REPAIR_FULL			:number = 6;	// 修理耐久已满的物品
		public static BAG_RESULT_BAG_NOT_EXIST			:number = 7;	// 包裹不存在
		public static BAG_RESULT_POS_NOT_EXIST			:number = 8;	// 包裹位置不存在
		public static BAG_RESULT_DESTROY_TOOMUCH			:number = 9;	// 数量不够删
		public static BAG_RESULT_BAN_FOR_TRADE			:number = 10;	// 交易中不允许操作
		public static BAG_RESULT_SPLIT_FAILURE			:number = 11;	// 物品拆分失败
		public static BAG_RESULT_LACK_USER			:number = 12;	// 数量不够删
		public static BAG_RESULT_BAG_FULL			:number = 13;	// 包裹放不下
		public static BAG_RESULT_MAX_COUNT			:number = 14;	// 超过最大拥有数
		public static BAG_RESULT_SELL_BIND			:number = 15;	// 定物品不允许出售
		public static BAG_RESULT_REPAIR_OK			:number = 16;	// 铜钱宝箱开启成功
		public static BAG_RESULT_REPAIR_MONEY_LACK			:number = 17;	// 钱不够无法修理
		public static BAG_RESULT_EXTENSION_BAG			:number = 18;	// 包裹不支持扩展
		public static BAG_RESULT_EXTENSION_MAX_SIZE			:number = 19;	// 包裹大小已经最大
		public static BAG_RESULT_EXTENSION_MATERIAL_LACK			:number = 20;	// 包裹扩展材料不足
		public static BAG_RESULT_EXTENSION_TRADE			:number = 21;	// 交易中不允许包裹扩展
		public static BAG_RESULT_USE_ITEM_COUNT_MAX			:number = 22;	// 使用物品数量达到上限
		public static BAG_RESULT_NOT_ITEM			:number = 23;	// 没开出物品
		public static BAG_RESULT_ITEM_USEING			:number = 24;	// 物品使用中
		public static BAG_RESULT_GET_ITEMS			:number = 25;	// 获得物品（元宝卡）
		public static BAG_RESULT_USE_ITEMS			:number = 26;	// 使用物品（装备宝箱）
		public static BAG_RESULT_GET_ITEMS_ORANGE			:number = 27;	// 开启橙色装备
		public static BAG_RESULT_USE_ITEMS_GENERALS			:number = 28;	// 使用物品（将魂使用）
		public static BAG_RESULT_GET_ITEMS_CABX			:number = 29;	// 获得 财神宝箱
		public static BAG_RESULT_GET_ITEMS_CABX_BUFF			:number = 30;	// 获得 财神宝箱的buff 提示
		public static BAG_RESULT_ALREADY_KAIGUANG			:number = 31;	// 设备已经开光
		public static BAG_RESULT_EXCHANGE_SUCCESS			:number = 32;	// 穿上装备成功
		public static BAG_RESULT_OPEN_ITEMS_SUCCESS			:number = 33;	// 打开物品成功（用于概率获得）
		public static BAG_RESULT_OPEN_ITEMS_FAIL			:number = 34;	// 打开物品失败（用于概率获得）
		public static BAG_RESULT_GET_ITEMS_GENERALS_EQUIP			:number = 35;	// 使用物品获得武将装备
		public static BAG_RESULT_GET_SHOWHAND_JIEZHI			:number = 36;	// 获得梭哈戒指
		public static BAG_RESULT_USE_WUJIANG_EXP_CARD			:number = 37;	// 使用武将经验卡
		public static BAG_RESULT_USE_ITEMS_SUCCESS			:number = 38;	// 物品使用成功
		public static BAG_RESULT_BAG_FULL_SEND_MAIL			:number = 39;	// 包裹已满 发送邮箱提示
		public static BAG_RESULT_BAG_FULL_AUTO_SELL			:number = 40;	// 包裹已满自动出售
		public static BAG_RESULT_BAG_XIULIAN_USE			:number = 41;	// 使用修炼丹获得经验
		public static BAG_RESULT_BAG_SORT_CD			:number = 42;	// 整理功能冷却中
		// 交易操作返回
		public static TRADE_RESULT_TYPE_NOT_TARGET			:number = 1;	// 没有交易对象
		public static TRADE_RESULT_TYPE_TRADEING			:number = 2;	// 已经交易中无法继续处理交易申请
		public static TRADE_RESULT_TYPE_NOT_TRADE			:number = 3;	// 非交易进行中无效操作
		public static TRADE_RESULT_TYPE_BAG_SIZE			:number = 4;	// 包裹空间不足交易失败
		public static TRADE_RESULT_TYPE_UNRECOGNISED			:number = 5;	// 未确认交易物品
		public static TRADE_RESULT_TYPE_TARGET_CANCEL			:number = 6;	// 对方交已取消交易
		public static TRADE_RESULT_TYPE_LACK_MONEY			:number = 7;	// 金钱不足
		public static TRADE_RESULT_TYPE_IS_BIND			:number = 8;	// 绑定物品不允许交易
		// 聊天操作返回
		public static CHAT_RESULT_NOT_PLAYER			:number = 1;	// 找不到玩家
		public static CHAT_RESULT_IS_GAG			:number = 2;	// 被禁言
		public static CHAT_LEVEL_WHISPER_LEVEL_NO			:number = 3;	// 私聊等级不足
		public static CHAT_LEVEL_WORLD_LEVEL_NO			:number = 4;	// 世界聊天等级不足
		public static CHAT_RESULT_CHECK_LIMIT			:number = 5;	// 您说话太快了，赶紧练级等等再聊天吧…
		public static CHAT_RESULT_NO_FACTION			:number = 6;	// 你暂无帮派
		public static CHAT_RESULT_NO_GROUP			:number = 7;	// 你暂无队伍
		// 领取补偿礼包操作返回
		public static RECEIVE_GIFT_PACKS_NOT_FIND			:number = 1;	// 找不到这条补偿礼包
		public static RECEIVE_GIFT_PACKS_CHAR_ERROR			:number = 2;	// 这礼包不是你的
		public static RECEIVE_GIFT_PACKS_CHAR_CREATE			:number = 3;	// 礼包指定的发放起始时间在你角色创建时间之前
		public static RECEIVE_GIFT_PACKS_RECEIVED			:number = 4;	// 该礼包你已经领取过了
		public static RECEIVE_GIFT_PACKS_ONLINE_AWARD			:number = 5;	// 在线礼包奖励
		public static RECEIVE_GIFT_PACKS_ONLINE_XIANSHI			:number = 6;	// 在线礼包显示用
		public static RECEIVE_GIFT_PACKS_FIRST_RECHARGE_GIFT			:number = 7;	// 首充礼包显示用
		public static RECEIVE_GIFT_PACKS_DAY_RECHARGE_GIFT			:number = 8;	// 每日充礼包显示用
		// 任务相关枚举
		public static INVALIDREASON_QUEST_FAILED_LOW_LEVEL			:number = 1;	//  等级太低 You are not high enough level for that quest.
		public static INVALIDREASON_QUEST_FAILED_WRONG_RACE			:number = 2;	//  这个任务对于你的角色类别是无效的 That quest is not available to your race.
		public static INVALIDREASON_QUEST_ALREADY_DONE			:number = 3;	//  任务已经完成 You have completed that quest.
		public static INVALIDREASON_QUEST_ONLY_ONE_TIMED			:number = 4;	//  任务只能做一次 You can only be on one timed quest at a time.
		public static INVALIDREASON_QUEST_ALREADY_ON			:number = 5;	//  已经在任务中 You are already on that quest.
		public static INVALIDREASON_QUEST_FAILED_EXPANSION			:number = 6;	//  物品太少 This quest requires an expansion enabled account.
		public static INVALIDREASON_QUEST_ALREADY_ON2			:number = 7;	//  已经在任务中 ? You are already on that quest.
		public static INVALIDREASON_QUEST_FAILED_MISSING_ITEMS			:number = 8;	//  没有完成任务需要的物品 You don't have the required items with you. Check storage.
		public static INVALIDREASON_QUEST_FAILED_NOT_ENOUGH_MONEY			:number = 9;	//  没有足够的金钱完成任务 You don't have enough money for that quest.
		public static INVALIDREASON_DAILY_QUESTS_REMAINING			:number = 10;	//  你已经完成了每天的25个任务 You have already completed 25 daily quests today.
		public static INVALIDREASON_QUEST_FAILED_CAIS			:number = 11;	//  有疲劳时间无法完成任务 You cannot complete quests once you have reached tired time.
		public static INVALIDREASON_DAILY_QUEST_COMPLETED_TODAY			:number = 12;	//  已经完成当天的任务 You have completed that daily quest today.
		public static INVALIDREASON_QUEST_FINISH_ALL_RIHUAN			:number = 13;	// 完成所有日环任务了
		public static QUEST_TYPE_PROCESS			:number = 14;	// 任务进度, 名字:1/1
		// 购买商品
		public static NPC_BUY_ITEM_NO_EXIST			:number = 0;	// 物品不存在
		public static NPC_BUY_ITEM_UNDER			:number = 1;	// 下架的物品
		public static NPC_BUY_ITEM_NO_OPEN			:number = 2;	// 商品还未到开放时间
		public static NPC_BUY_ITEM_OUT_TIME			:number = 3;	// 商品已过期
		public static NPC_BUY_BAG_OUT_SIZE			:number = 4;	// 包裹放不下了
		public static NPC_BUY_MONEY_NO_ENOUGH			:number = 5;	// 钱不够了
		public static NPC_BUY_MONEY_TRANSFINITE			:number = 6;	// 购买金额过大
		public static NPC_BUY_SELL_OUT			:number = 7;	// 超出商品限购次数
		// 副本
		public static FUBEN_OPRATE_NO_GROUP_STATE			:number = 0;	// 玩家不在组队状态
		public static FUBEN_OPRATE_NOT_TWO_PEOPLE			:number = 1;	// 队伍不是2个人
		public static FUBEN_OPRATE_NO_ENERGY			:number = 2;	// 体力不足
		public static FUBEN_OPRATE_NO_MONEY			:number = 3;	// 元宝不足
		public static FUBEN_OPRATE_TEAM_NO_LEVEL			:number = 4;	// 队友等级不足
		public static FUBEN_OPRATE_TEAM_NO_ENERGY			:number = 5;	// 队友体力不足
		public static FUBEN_OPRATE_NO_GROUP			:number = 6;	// 队伍已经解散
		public static FUBEN_OPRATE_SEND_TEAM_FRIEND			:number = 7;	// 邀请队友进入组队副本
		public static FUBEN_OPRATE_TEAM_REFUSE_ENETR			:number = 8;	// 队友拒绝进入组队副本
		public static FUBEN_OPRATE_TEAM_ON_FUBEN_MAP			:number = 9;	// 队友在副本地图中
		public static FUBEN_OPRATE_TEAM_HAVE_FLAGS			:number = 10;	// 队友已经发起邀请了
		public static FUBEN_OPRATE_REFRESH_BOSS			:number = 11;	// 副本刷出boss
		public static FUBEN_OPRATE_KILLED_BOSS			:number = 12;	// 玩家成功击杀了boss
		public static FUBEN_OPRATE_MORE_TIMES			:number = 13;	// 全屏秒杀超过最大次数
		public static FUBEN_OPRATE_NO_CREATURES			:number = 14;	// 全屏秒杀当前没有怪物
		// 跨服
		public static KUAFU_OPERATE_CONN_DISCONN			:number = 0;	// 游戏服与世界服的链接断开了
		public static KUAFU_OPERATE_HASNOT_REGISTER			:number = 1;	// 本服还没有向世界服注册成功
		// 排行榜
		public static RANK_LIST_OPERATE_SUCCEED			:number = 0;	// 成功
		public static RANK_LIST_OPERATE_TYPE_ERROR			:number = 1;	// 查询类型错误
		public static RANK_LIST_OPERATE_OUT_OF_RANGE			:number = 2;	// 查询范围超出界限
		public static RANK_LIST_OPERATE_MAX_LIKE			:number = 4;	// 点赞已超过最大次数
		public static RANK_LIST_OPERATE_HAS_LIKE			:number = 5;	// 已点过赞了
		public static ACTIVITY_OPERATE_NOTVIP			:number = 0;	// 你不是vip无法领取vip奖励
		public static ACTIVITY_OPERATE_NOENOUGH			:number = 1;	// 活跃度不够无法领取
		public static ACTIVITY_OPERATE_HASGET			:number = 2;	// 已经领取过该奖励
		public static ACHIEVE_OPERATE_NO_FIND			:number = 0;	// 找不到成就
		public static ACHIEVE_OPERATE_NO_GET			:number = 1;	// 尚未达成成就
		public static ACHIEVE_OPERATE_HASGET			:number = 2;	// 已经领取过成就奖励
		public static ACHIEVE_OPERATE_NO_ALL			:number = 3;	// 总成就不够无法领取
		public static ACHIEVE_OPERATE_TITLE_SUC			:number = 4;	// 设置称号成功
		public static ACHIEVE_OPERATE_TITLE_FAL			:number = 5;	// 称号不存在无法设置
		public static ACHIEVE_OPERATE_NO_MONEY			:number = 6;	// 钱不够了不能找回
		public static ATHLETICS_OPERATE_NO_LEV			:number = 1;	// 等级不够{1}，不能参加3v3
		public static ATHLETICS_OPERATE_NO_FORCE			:number = 2;	// 战力不够{1}，不能参加3v3
		public static ATHLETICS_OPERATE_NO_OPEN			:number = 3;	// 不在活动时间，不能参加
		public static ATHLETICS_OPERATE_NO_TIME_BUY			:number = 4;	// 3v3次数已用完，可以购买次数
		public static ATHLETICS_OPERATE_NO_TIME			:number = 5;	// 3v3次数已用完，请明天再来
		public static ATHLETICS_OPERATE_IN_MATCH			:number = 6;	// 正在匹配中
		public static ATHLETICS_OPERATE_MAX_BUY			:number = 7;	// 超出最大购买次数
		public static ATHLETICS_OPERATE_NO_MONEY			:number = 8;	// 超出最大购买次数
		public static ATHLETICS_OPERATE_HAS_DAY_REWARD			:number = 9;	// 已经领取该奖励
		public static ATHLETICS_OPERATE_NO_DAY_REWARD			:number = 10;	// 尚未到达次数{1}
		public static ATHLETICS_OPERATE_BUFF_OCCUR			:number = 11;	// buff产生
		public static DOUJIAN_OPERATE_NO_LEV			:number = 0;	// 等级不够，需要{0}才能参与斗剑台
		public static DOUJIAN_OPERATE_ZHUCHENG			:number = 1;	// 只能在主城中参加活动
		public static DOUJIAN_OPERATE_NO_TIME			:number = 2;	// 挑战次数已满
		public static DOUJIAN_OPERATE_IN_CD			:number = 3;	// 挑战CD中
		public static DOUJIAN_OPERATE_MAX_TIME			:number = 4;	// 超过最大购买次数
		public static DOUJIAN_OPERATE_NO_MONEY			:number = 5;	// 元宝不足购买斗剑次数
		public static DOUJIAN_OPERATE_NO_MONEY_CD			:number = 6;	// 元宝不足不能清理CD
		public static DOUJIAN_OPERATE_SELF_BATTLE			:number = 7;	// 自己正在被别人挑战
		public static DOUJIAN_OPERATE_OTHER_BATTLE			:number = 8;	// 挑战的人正在被别人挑战
		public static DOUJIAN_OPERATE_COUNTDOWN			:number = 9;	// 刷新在冷却中
		public static DOUJIAN_OPERATE_REFRESH			:number = 10;	// 刷新完成
		// 游戏关闭信息
		public static PLAYER_CLOSE_OPERTE_APPD_ONE1			:number = 1000;	// 插入单个物品时，包裹id 超过最大值
		public static PLAYER_CLOSE_OPERTE_APPD_ONE2			:number = 1001;	// 创建玩家其他的对象的时候，发现之前已经创建过了
		public static PLAYER_CLOSE_OPERTE_APPD_ONE3			:number = 1002;	// 托管到期
		public static PLAYER_CLOSE_OPERTE_APPD_ONE4			:number = 1003;	// GM命令 踢人
		public static PLAYER_CLOSE_OPERTE_APPD_ONE5			:number = 1004;	// GM命令 回档数据
		public static PLAYER_CLOSE_OPERTE_APPD_ONE6			:number = 1005;	//  踢玩家下线
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE4			:number = 2001;	// 帐号信息不完整
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE5			:number = 2002;	// Char_Create put  fail!
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE6			:number = 2003;	// 登录时候不是我的角色
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE7			:number = 6;	// 待定
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE8			:number = 2004;	// 跨服回来的玩家 m_player 不存在
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE9			:number = 2005;	// 初始化数据库数据失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE10			:number = 2006;	// 看看有没有玩家数据需要修复或者升级的
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE11			:number = 2007;	// 重设元宝数量 取数据时失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE12			:number = 2008;	// 踢人
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE13			:number = 2009;	// 如果连接不存在,则根据解开的session结果进行创建对应的session实例(on_create_conn_get_session create_sesstion duplicate)
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE14			:number = 2010;	// 客户端连接失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE15			:number = 2011;	// 把玩家由pk服回到游戏服,登录失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE16			:number = 2012;	// 检测跨服玩家是否可以登陆 -玩家不存在
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE17			:number = 2013;	// 检测跨服玩家是否可以登陆 -超时
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE18			:number = 2014;	// 登陆队列 context->GetGuid().empty(）
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE19			:number = 2015;	// 合服检测 手游下线
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE20			:number = 2016;	// 通知场景服玩家加入地图 m_scened_conn不存在
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE21			:number = 2017;	// 玩家加入地图实例时，玩家binlg不存在 
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE22			:number = 2018;	// 玩家加入地图 创建实例失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE23			:number = 2019;	// 如果已登录过 !m_account.empty()
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE24			:number = 2020;	// 帐号名称超长
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE25			:number = 2021;	// 验证是否可以登录本服验证失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE26			:number = 2022;	// 账户表数据不存在
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE27			:number = 2023;	// 玩家已在线关闭掉旧链接
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE28			:number = 2024;	// 手游登录，但是还没有玩家角色
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE39			:number = 2025;	// 数据准备完毕，玩家开始登录 玩家不存在
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE40			:number = 2026;	// 获取sessionKey对象,已经登录过
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE41			:number = 2027;	// 获取sessionKey对象，帐户名称，并且判断一下是否超长(超长则失败)
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE42			:number = 2028;	// 获取sessionKey对象，Get_Session: other_data size is wrong
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE43			:number = 2029;	// 获取sessionKey对象，验证session_key是否可以登录这个服务器（为不可登录时候断开）
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE44			:number = 2030;	// 获取sessionKey对象，LogindContext::Get_Session:%s load account fail(获取帐号表数据异常)
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE45			:number = 2031;	// 获取sessionKey对象，LogindContext::Get_Session:%s Get_Chars_List fail（获取角色列表数据异常）
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE46			:number = 2032;	// 跨服读取数据失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE47			:number = 2033;	// 运气不好，登录时碰上正在释放自己数据
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE48			:number = 2034;	// 合服检测，从服玩家状态 不为 STATUS_LOGGEDIN
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE49			:number = 2035;	// 封号
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE50			:number = 2036;	// 踢人
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE51			:number = 2037;	// 玩家不存在时关闭连接 LuaPlayerLogin %s, but not found
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE52			:number = 2038;	// 角色在其他地方登陆
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE53			:number = 2039;	// 登陆是无法获得数据
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE54			:number = 2040;	// 登陆时 player login call puts fail %s, fd %u
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE55			:number = 2041;	// on_create_conn_get_session create_mobile_context duplicate
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE56			:number = 2042;	// 登陆失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE57			:number = 2045;	// Gm命令 @自爆
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE58			:number = 2043;	// PK服登陆数据异常
		public static PLAYER_CLOSE_OPERTE_LOGDIN_ONE59			:number = 2044;	// 从数据库读取玩家数据失败
		public static PLAYER_CLOSE_OPERTE_LOGDIN_2046			:number = 2046;	// 一个角色对应两个账号	
		public static PLAYER_CLOSE_OPERTE_LOGDIN_2047			:number = 2047;	// 改名字的时候找不到account，刷新就可以过了
		public static PLAYER_CLOSE_OPERTE_LOGDIN_2048			:number = 2048;	// session的account不等于player的account,简单来说,串号了.
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE29			:number = 3001;	// 停止移动，地图模板为null
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE30			:number = 3002;	// 对象移动，地图模板为null
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE31			:number = 3003;	// 对象移动的时候  状态不为 STATUS_LOGGEDIN  时候 （assert error: Handle_Unit_Move  ASSERT(status_ == STATUS_LOGGEDIN)）
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE32			:number = 3004;	// 传送是 状态不为 STATUS_LOGGEDIN （ScenedContext::Teleport status_ != STATUS_LOGGEDIN）
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE33			:number = 3005;	// 如果玩家未正确的加入地图，这个时间传送也是失败的
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE34			:number = 3006;	// 任务链条中断 assert error: Handle_QuestGiver_Status_Query  ASSERT(questGetter)
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE35			:number = 3007;	// 玩家被杀死时，地图数据不存在 Player::OnKilled ASSERT(GetMap())
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE36			:number = 3008;	// 加入地图宠物不存在的时候  Player::OnJoinMap ASSERT(m_pets.empty())
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE37			:number = 3009;	// 任务管理者不存在的时候 Player::Create ASSERT(!m_questMgr)
		public static PLAYER_CLOSE_OPERTE_SCREND_ONE38			:number = 3010;	// 传送超时1分钟
		public static PLAYER_CLOSE_OPERTE_POLICED_4001			:number = 4001;	// 在日志服重复登录
		public static OPERTE_TYPE_FACTION_IS_HAVE			:number = 0;	// 你已经在帮派中
		public static OPERTE_TYPE_FACTION_NAME_ERR			:number = 1;	// 帮派名称超过6个字符
		public static OPERTE_TYPE_FACTION_NAME_HAVE_FUCK			:number = 2;	// 帮派名称中有非法字符
		public static OPERTE_TYPE_FACTION_NAME_REPEAT			:number = 3;	// 帮派名称重复
		public static OPERTE_TYPE_FACTION_CREATE_MAX			:number = 4;	// 帮派数量达到上限
		public static OPERTE_TYPE_FACTION_CREATE_COST			:number = 5;	// 元宝不足无法创建帮派
		public static OPERTE_TYPE_FACTION_NOT_MANAGER			:number = 6;	// 不是帮主或副帮主无法编辑
		public static OPERTE_TYPE_FACTION_NOTICE_ERR			:number = 7;	// 帮派公告超过144个字符
		public static OPERTE_TYPE_FACTION_NOTICE_ERR_PB			:number = 8;	// 帮派公告包含非法字符
		public static OPERTE_TYPE_FACTION_LEV_LOW			:number = 9;	// 等级不够，不能加入帮派
		public static OPERTE_TYPE_FACTION_MEMBER_MAX_COUNT			:number = 10;	// 帮派人数已满无法加入
		public static OPERTE_TYPE_FACTION_JOIN_SUCESS			:number = 11;	// 恭喜你加入帮派
		public static OPERTE_TYPE_FACTION_FACTION_REFUSED_JOIN			:number = 12;	// 你被拒绝加入帮派
		public static OPERTE_TYPE_FACTION_KICKED			:number = 13;	// 你被移出帮派
		public static OPERTE_TYPE_FACTION_KICK_SUCCESS			:number = 14;	// 踢出帮派成员
		public static OPERTE_TYPE_FACTION_MAX_ZHIWEI			:number = 15;	// 职位人数已满
		public static OPERTE_TYPE_FACTION_APPOINT_SUCCESS			:number = 16;	// 任命成功
		public static OPERTE_TYPE_FACTION_PROMOTED			:number = 17;	// 你被任命为
		public static OPERTE_TYPE_FACTION_APPOINT_NOSELF			:number = 18;	// 自己不能任命自己 
		public static OPERTE_TYPE_FACTION_DONATIONMAX			:number = 19;	// 捐献次数超过最大次数
		public static OPERTE_TYPE_FACTION_DONATION_GOLD			:number = 20;	// 捐献所需金币不够
		public static OPERTE_TYPE_FACTION_DONATION_YB			:number = 21;	// 捐献所需元宝不够
		public static OPERTE_TYPE_FACTION_SHOP_NUMLOW			:number = 22;	// 商品剩余数量不足无法购买
		public static OPERTE_TYPE_FACTION_DEVOTE			:number = 23;	// 帮贡不足
		public static OPEATE_TYPE_FACTION_MONEY_ERR			:number = 24;	// 帮派资金不足
		public static OPEATE_TYPE_FACTION_LEVEL_UP			:number = 25;	// 帮派升级成功
		public static OPEATE_TYPE_FACTION_NOT_JOIN			:number = 26;	// 没有可以加入的帮派
		public static OPERTE_TYPE_FACTION_PLAYER_OFFLINE			:number = 40;	// 对方不在线,无法加入成员
		public static OPERTE_TYPE_FACTION_BOSS_START			:number = 50;	// 召唤boss
		public static OPERTE_TYPE_FACTION_GIFT_THANK			:number = 59;	// 感谢完成
		public static OPERTE_TYPE_FACTION_GIFT_THANK_ALL			:number = 60;	// 全部感谢完成
		public static OPERTE_TYPE_FACTION_GIFT_GET_EXREWARD			:number = 61;	// 领取成功
		public static OPERTE_TYPE_FACTION_GIFT_GET_EXREWARD_ALL			:number = 62;	// 全部领取成功
		public static OPERTE_TYPE_FACTION_GIFT_SEND			:number = 63;	// 赠送成功
		public static OPERTE_TYPE_FACTION_GIFT_SEND_FAIL			:number = 64;	// 赠送成功
		public static OPERTE_TYPE_FACTION_GIFT_NOTICE			:number = 65;	// 礼物广播
		public static OPERTE_TYPE_FACTION_BOSSDEFENSE_TIME_ERROR			:number = 66;	// 非法时间 无法挑战boss
		public static OPERTE_TYPE_FACTION_NAME_NOT_CHINESE			:number = 67;	// 包含中文以外字符
		public static OPERTE_TYPE_FACTION_MATCH_DECIDE_FIRST			:number = 68;	// 家族战第一轮对阵表已产生
		public static OPERTE_TYPE_FACTION_MATCH_OPEN_FIRST			:number = 69;	// 家族战第一轮比赛开放进入,参赛家族成员请及时进入战场
		public static OPERTE_TYPE_FACTION_MATCH_START_FIRST			:number = 70;	// 家族战第一轮比赛正式开战
		public static OPERTE_TYPE_FACTION_MATCH_DECIDE_SECOND			:number = 71;	// 家族战第二轮对阵表已产生
		public static OPERTE_TYPE_FACTION_MATCH_OPEN_SECOND			:number = 72;	// 家族战第二轮比赛开放进入,参赛家族成员请及时进入战场
		public static OPERTE_TYPE_FACTION_MATCH_START_SECOND			:number = 73;	// 家族战第二轮比赛正式开战
		public static OPERTE_TYPE_FACTION_MATCH_FINISH			:number = 74;	// 恭喜家族 {1} 成为家族战盟主
		public static OPERTE_TYPE_FACTION_MATCH_CANNOT_JOIN			:number = 75;	// 不能加入家族
		public static OPERTE_TYPE_FACTION_STORE_IS_FULL			:number = 76;	// 家族商店已满
		public static OPERTE_TYPE_SOCIAL_HAS_SEND			:number = 1;	// 好友请求信息已发送
		public static OPERTE_TYPE_SOCIAL_NOT_FIND			:number = 2;	// 角色不存在或者角色不在线
		public static OPERTE_TYPE_SOCIAL_SELF_FULL			:number = 3;	// 自己好友列表已满
		public static OPERTE_TYPE_SOCIAL_TARGET_FULL			:number = 4;	// 对方好友列表已满
		public static OPERTE_TYPE_SOCIAL_ALREADY_FRIEND			:number = 5;	// 对方已经是你的好友
		public static OPERTE_TYPE_SOCIAL_ADD_MYSELF			:number = 6;	// 不能自己添加自己为好友
		public static OPERTE_TYPE_SOCIAL_HAS_SEND_ADD			:number = 7;	// 已经发送申请
		public static OPERTE_TYPE_SOCIAL_NO_MONEY			:number = 8;	// 元宝或者金币不足
		public static OPERTE_TYPE_SOCIAL_NOT_ENEMY			:number = 9;	// 对方不是仇人
		public static OPERTE_TYPE_SOCIAL_ENEMY_OFFLINE			:number = 10;	// 对方处于离线中
		public static OPERTE_TYPE_SOCIAL_ENEMY_NOT_IN_FIELD			:number = 11;	// 对方不在野外
		public static OPERTE_TYPE_SOCIAL_REVENGE_TIMES_NOT_ENOUGH			:number = 12;	// 复仇传送次数不足
		public static OPERTE_TYPE_SOCIAL_RENAME_SUCCESS			:number = 13;	// 改名成功
		public static OPERTE_TYPE_SOCIAL_OTHNER_FACTION			:number = 14;	// 对方已在帮派
		public static OPERTE_TYPE_SOCIAL_SAME_FACTION			:number = 15;	// 对方已在同帮派
		// 托管
		public static HOSTING_OPERTE_IS_SELF			:number = 0;	// 无法对自己操作
		public static HOSTING_OPERTE_LEVEL_NOT			:number = 1;	// 等级不足
		public static HOSTING_OPERTE_IS_HOSTING			:number = 2;	// 托管中
		public static HOSTING_OPERTE_IS_HOSTING_APPLY			:number = 3;	// 托管申请
		public static HOSTING_OPERTE_FRIEND_NOT			:number = 4;	// 好友不存在
		public static HOSTING_OPERTE_HAS_NOT_24H			:number = 5;	// 还没到24小时
		public static HOSTING_OPERTE_FRIEND_OUTLINE			:number = 6;	// 好友不在线
		public static HOSTING_OPERTE_FRIEND_ERR			:number = 7;	// 托管好友错误
		public static HOSTING_OPERTE_NOT_HOSTING			:number = 8;	// 不在托管中
		public static HOSTING_OPERTE_FRIEND_ONLINE			:number = 9;	// 好友在线
		public static HOSTING_OPERTE_LOGIN_HOSTING			:number = 10;	// 托管登录中
		public static HOSTING_OPERTE_FRIEND_APPLY			:number = 11;	// 申请发送
		public static HOSTING_OPERTE_LOGIN			:number = 12;	// 登录
		public static HOSTING_OPERTE_SUCCESS			:number = 13;	// 托管申请成功
		public static HOSTING_OPERTE_CANCEL			:number = 14;	// 取消托管
		public static HOSTING_OPERTE_REFUSED			:number = 15;	// 拒绝托管
		public static HOSTING_OPERTE_NOT_DUE_TO			:number = 16;	// 托管未到期
		public static HOSTING_OPERTE_FRIEND_HOSTING_LOGIN			:number = 17;	// 对方托管登录中，无法操作
		public static HOSTING_OPERTE_FRIEND_NOT_HAS_YOU			:number = 18;	// 对方好友列表没有你
		// 强化
		public static STRENGTH_OPERTE_FAIL			:number = 0;	// 强化失败
		// 切换战斗模式
		public static BATTLE_MODE_OPERTE_PEACE_MODE_DENY			:number = 0;	// 战斗中不能切换和平模式
		public static BATTLE_MODE_OPERTE_PEACE_MODE_IN_CD			:number = 1;	// 和平模式在CD中
		//  野外BOSS
		public static FIELD_BOSS_OPERTE_WILL_START			:number = 1;	// 野外BOSS即将在{1}分钟后开启, 请大家安排好时间
		public static FIELD_BOSS_OPERTE_WILL_OCCUR			:number = 2;	// 野外boss即将出现，请各位大侠做好准备
		public static FIELD_BOSS_OPERTE_OCCUR			:number = 3;	// 野外boss已经在各个地图刷新，请各位大侠火速前往击杀 查看详情
		public static FIELD_BOSS_OPERTE_BOSS_BORN			:number = 4;	// {1}已出现在{2}，请各位大侠火速前往击杀 立即前往
		public static FIELD_BOSS_OPERTE_BOSS_KILL			:number = 5;	// {1}已被成功击杀！恭喜{2}获得{3}1分钟的优先开启权利
		public static FIELD_BOSS_OPERTE_PROTECT			:number = 6;	// 九龙宝箱保护时间结束，静待各位大侠开启
		public static FIELD_BOSS_OPERTE_PICKED			:number = 7;	// 恭喜{1}最终开启九龙宝箱，获得XXXX
		public static FIELD_BOSS_OPERTE_TOO_FAR			:number = 8;	// 太远了，你不可能开启这个宝箱
		//  世界BOSS
		//  OPERTE_TYPE_WORLD_BOSS
		public static WORLD_BOSS_OPERTE_NOT_ENROLL			:number = 0;	// 本次活动您未报名，无法参加
		public static WORLD_BOSS_OPERTE_WILL_START			:number = 1;	// 世界boss即将开启，请各位大侠做好准备
		public static WORLD_BOSS_OPERTE_WILL_ROLL1			:number = 2;	// 恭喜{1}赢得本次拼点奖励，BOSS在3秒后恢复正常
		public static WORLD_BOSS_OPERTE_WILL_ROLL2			:number = 3;	// 恭喜{1}赢得本次拼点奖励，现在可自由离开战场
		public static WORLD_BOSS_OPERTE_ENROLL			:number = 4;	// 世界BOSS开始报名
		//  坐骑骑乘
		//  OPRATE_TYPE_MOUNT_QICHENG
		public static MOUNT_QICHENG_FIGHT			:number = 0;	// 战斗状态不能骑乘
		public static MOUNT_QICHENG_JUMP			:number = 1;	// 跳跃状态不能骑乘
		//  传送
		// OPRATE_TYPE_TELEPORT
		public static TELEPORT_OPRATE_PVP_STATE			:number = 0;	// pvp状态不能传送
		//  升级操作
		// OPRATE_TYPE_UPGRADE
		public static UPGRADE_OPRATE_SKILL_SUCCESS			:number = 0;	// 技能升级成功
		public static UPGRADE_OPRATE_MOUNT_EXP			:number = 1;	// 坐骑经验+{1}
		public static UPGRADE_OPRATE_MOUNT_STAR			:number = 2;	// 坐骑星级+1
		public static UPGRADE_OPRATE_MOUNT			:number = 3;	// 进阶成功
		public static UPGRADE_OPRATE_ANGLE_SKILL			:number = 4;	// 怒气技能进阶成功
		public static UPGRADE_OPRATE_BLESS_SUCCESS			:number = 5;	// 部位升级成功
		public static UPGRADE_OPRATE_BLESS_EXP			:number = 6;	// 部位经验+{1}
		public static UPGRADE_OPRATE_GEM_SUCCESS			:number = 7;	// 宝石激活成功
		public static UPGRADE_OPRATE_GEM_EXP			:number = 8;	// 宝石经验+{1}
		public static UPGRADE_OPRATE_TALISMAN_ACTIVE			:number = 9;	// 法宝激活成功
		public static UPGRADE_OPRATE_TALISMAN_LVUP			:number = 10;	// 法宝注灵
		public static UPGRADE_OPRATE_WINGS_ACTIVE			:number = 11;	// 神羽激活成功
		public static UPGRADE_OPRATE_WINGS_BLESS			:number = 12;	// 神羽祝福成功
		public static UPGRADE_OPRATE_WINGS_RANKUP			:number = 13;	// 神羽升阶成功
		public static UPGRADE_OPRATE_WINGS_STRENGTH_SUCESS			:number = 14;	// 神羽强化成功
		public static UPGRADE_OPRATE_WINGS_STRENGTH_FAIL			:number = 15;	// 神羽强化失败
		public static UPGRADE_OPRATE_EQUIPDEVELOP_STRENGTH_SUCCESS			:number = 16;	// 装备部位强化成功
		public static UPGRADE_OPRATE_EQUIPDEVELOP_REFINE_STAR_SUCCESS			:number = 17;	// 装备部位升星成功
		public static UPGRADE_OPRATE_EQUIPDEVELOP_REFINE_STAR_FAIL			:number = 18;	// 装备部位升星失败
		public static UPGRADE_OPRATE_EQUIPDEVELOP_REFINE_RANK_SUCCESS			:number = 19;	// 装备部位升阶成功
		public static UPGRADE_OPRATE_EQUIPDEVELOP_REFINE_RANK_FAIL			:number = 20;	// 装备部位升阶失败
		public static UPGRADE_OPRATE_EQUIPDEVELOP_GEM_ACTIVE_SUCCESS			:number = 21;	// 装备宝石激活成功
		public static UPGRADE_OPRATE_EQUIPDEVELOP_GEM_LVUP_SUCCESS			:number = 22;	// 装备宝石强化成功
		public static UPGRADE_OPRATE_EQUIPDEVELOP_WASHATTRS_WASH			:number = 23;	// 装备洗炼完成
		public static UPGRADE_OPRATE_EQUIPDEVELOP_WASHATTRS_SAVE			:number = 24;	// 装备洗炼保存
		public static UPGRADE_OPRATE_EQUIPDEVELOP_BONUS_STRENGTH			:number = 25;	// 装备强化奖励
		public static UPGRADE_OPRATE_EQUIPDEVELOP_BONUS_REFINE			:number = 26;	// 装备精炼奖励
		public static UPGRADE_OPRATE_EQUIPDEVELOP_BONUS_GEM			:number = 27;	// 装备镶嵌奖励
		public static UPGRADE_OPRATE_FACTIONSKILL_LVUP			:number = 28;	// 家族技能升级成功
		public static UPGRADE_OPRATE_MOUNT_ILLUSION_ACTIVE			:number = 29;	// 坐骑皮肤激活成功
		public static UPGRADE_OPRATE_CLOTH_ILLUSION_ACTIVE			:number = 30;	// 衣服外观激活成功
		public static UPGRADE_OPRATE_WEAPON_ILLUSION_ACTIVE			:number = 31;	// 武器外观激活成功
		public static UPGRADE_OPRATE_TITLE_ACTIVE			:number = 32;	// 称号激活成功
		public static UPGRADE_OPRATE_MOUNT_ILLUSION_SET			:number = 33;	// 坐骑幻化成功
		public static UPGRADE_OPRATE_MOUNT_ILLUSION_UNSET			:number = 34;	// 坐骑取消幻化
		public static UPGRADE_OPRATE_FASHION_ILLUSION_SET			:number = 35;	// 外观装备成功
		public static UPGRADE_OPRATE_FASHION_ILLUSION_UNSET			:number = 36;	// 外观取消装备
		public static UPGRADE_OPRATE_MOUNT_LEVEL_UP			:number = 37;	// 坐骑升级成功
		public static UPGRADE_OPRATE_MERIDIAN_LEVEL_UP			:number = 38;	// 经脉升级成功
		public static UPGRADE_OPRATE_MERIDIAN_UPGRADE			:number = 39;	// 经脉突破成功
		public static UPGRADE_OPRATE_WINGS_BLESS_NUM			:number = 40;	// 神羽祝福经验
		// 仙府夺宝
		// OPRATE_TYPE_XIANFU
		public static XIANFU_TYPE_BOSS_OCCUR			:number = 0;	// {1}已在{2}点出现, 击杀可掉落{3}
		public static XIANFU_TYPE_BOSS_KILL			:number = 1;	// {1}被{2}击杀, 掉落{3}个宝箱
		//  奖励来源对应的不同的提示信息
		public static REWARD_TYPE_ACTIVITY			:number = 0;	// 活动奖励获得
		public static REWARD_TYPE_RECHARGE			:number = 1;	// 充值赠送获得
		public static REWARD_TYPE_GIFT_PACKS			:number = 2;	// 补偿礼包获得
		public static REWARD_TYPE_QUEST			:number = 3;	// 任务完成奖励获得
		public static REWARD_TYPE_NEWPLAYER			:number = 4;	// 新手礼包获得
		public static REWARD_TYPE_OPEN_ITEM			:number = 5;	// 使用道具获得
		public static REWARD_TYPE_LOOT			:number = 6;	// 战利品
		public static REWARD_TYPE_GM_COMMAND			:number = 7;	// GM命令获得
		public static REWARD_TYPE_ITEM_BLEND			:number = 8;	// 物品合成获得
		public static REWARD_TYPE_SEVEN_DAY_GIFT			:number = 9;	// 连登礼包	
		public static REWARD_TYPE_JHM_GIFT			:number = 10;	// 激活码礼包
		public static REWARD_TYPE_OPEN_BOX			:number = 11;	// 开宝箱获得
		public static REWARD_TYPE_FUBEN_EWAIJINAGLI			:number = 12;	// 副本额外奖励
		public static REWARD_TYPE_CAPTURE_YAOHUN			:number = 13;	// 扑捉妖魂获得
		public static REWARD_TYPE_FSZL_EWAIJINAGLI			:number = 14;	// 飞升之路奖励
		public static REWARD_TYPE_PRESTIGE			:number = 15;	// 活跃度领取获得
		public static REWARD_TYPE_TIANDILINGKUANG			:number = 16;	// 天地灵矿领取获得
		public static REWARD_TYPE_PANTAOYUAN			:number = 17;	// 蟠桃园奖励
		public static REWARD_TYPE_WABAO			:number = 18;	// 挖宝获得
		public static REWARD_TYPE_HONGYAN			:number = 19;	// 红颜事件获得
		public static REWARD_TYPE_FORGE_DECOMPOSE			:number = 20;	// 锻造分解获得
		public static REWARD_TYPE_WORLD_BOSS_ROLL			:number = 21;	// 世界BOSSroll点
		public static REWARD_TYPE_VIP_INSTANCE_REWARD			:number = 22;	// vip副本奖励
		public static REWARD_TYPE_TRIAL_INSTANCE_REWARD			:number = 23;	// 试炼塔奖励
		public static REWARD_TYPE_ACHIEVE			:number = 24;	// 成就奖励
		public static REWARD_TYPE_SHOUCHONG			:number = 25;	// 首充奖励
		public static REWARD_TYPE_CHECKIN			:number = 26;	// 每日签到奖励
		public static REWARD_TYPE_GETBACK			:number = 27;	// 找回次数奖励
		public static REWARD_TYPE_TOTAL_CHECKIN			:number = 28;	// 每日累积签到奖励
		public static REWARD_TYPE_WELFARE_LEVEL			:number = 29;	// 福利等级奖励
		public static REWARD_TYPE_3V3_KUAFU			:number = 30;	// 3v3跨服奖励
		public static REWARD_TYPE_INSTANCE_SWEEP			:number = 31;	// 副本奖励扫荡奖励
		public static REWARD_TYPE_XIANFU			:number = 32;	// 仙府夺宝跨服奖励
		public static GEM_TYPE_CRIT			:number = 0;	// 宝石暴击
		public static MONEYTREE_TYPE_NORMAL			:number = 0;	// 普通
		public static MONEYTREE_TYPE_CRIT			:number = 1;	// 暴击
		public static NEED_NOTICE_TYPE_WING_RANKUP			:number = 0;	// 翅膀进阶
		public static NEED_NOTICE_TYPE_WING_STRENGTH			:number = 1;	// 翅膀强化
		public static NEED_NOTICE_TYPE_MOUNT_RANKUP			:number = 2;	// 坐骑进阶
		public static NEED_NOTICE_TYPE_TALISMAN_ACTIVE			:number = 3;	// 法宝激活
		public static NEED_NOTICE_TYPE_TALISMAN_LVUP			:number = 4;	// 法宝升级
		public static NEED_NOTICE_TYPE_TRIAL_WIN			:number = 5;	// 试炼塔
		public static NEED_NOTICE_TYPE_RISK_CHAPTER			:number = 6;	// 幻境挂机
		public static NEED_NOTICE_TYPE_DOUJIANTAI_RANKUP			:number = 7;	// 斗剑台
		public static NEED_NOTICE_TYPE_PAIWEI_RANKUP			:number = 8;	// 排位赛
		public static NEED_NOTICE_TYPE_ADVENTURE_ROB			:number = 9;	// 野外资源抢夺
		public static NEED_NOTICE_TYPE_ADVENTURE_ROBED			:number = 10;	// 野外资源被抢夺
		public static NEED_NOTICE_TYPE_REFINE_LVUP			:number = 11;	// 精炼达到X级
		public static NEED_NOTICE_TYPE_GEM_LVUP			:number = 12;	// 宝石达到X级
		public static NEED_NOTICE_TYPE_3V3_RANKUP			:number = 13;	// 3v3排行达到1~10
		public static NEED_NOTICE_TYPE_RECHARGE_LOTTERY			:number = 14;	// {1}投资{2}元宝获得{3}绑定元宝
		public static GROUP_NOTICE_TYPE_MEMBER_IN_INSTANCE			:number = 1;	// {1}正在副本中
		public static GROUP_NOTICE_TYPE_MEMBER_DECLINE			:number = 2;	// {1}拒绝加入
		public static GROUP_NOTICE_TYPE_MEMBER_NO_TIMES			:number = 3;	// {1}次数不足
		public static GROUP_NOTICE_TYPE_MEMBER_IS_OFFLINE			:number = 4;	// {1}已经下线
		public static GROUP_NOTICE_TYPE_PLAYER_IS_OFFLINE			:number = 5;	// 提示处于离线无法加入
		public static GROUP_NOTICE_TYPE_DENIED_JOIN_REQUEST			:number = 6;	// {1}拒绝申请消息
		public static GROUP_NOTICE_TYPE_KICKED			:number = 7;	// 被{1}踢消息
		public static GROUP_NOTICE_TYPE_BECOME_CAPTAIN			:number = 8;	// 成为队长消息
		public static GROUP_NOTICE_TYPE_DENIED_INVITE			:number = 9;	// {1}拒绝邀请消息
		public static GROUP_NOTICE_TYPE_MEMBER_FULL			:number = 10;	// {1}队伍已满
		public static GROUP_NOTICE_TYPE_ALREADY_HAVE_GROUP			:number = 11;	// {1}对方处于组队状态
		public static GROUP_NOTICE_TYPE_JOIN_SUCCESS			:number = 12;	// {1}加入成功
		public static GROUP_NOTICE_TYPE_JOIN_REQUEST			:number = 13;	// {1}请求已发送
		public static GIFTCODE_NOTICE_TYPE_INVALID			:number = 1;	// 无效兑换码
		public static GIFTCODE_NOTICE_TYPE_USED			:number = 2;	// 该兑换码已经被使用过了
		public static GIFTCODE_NOTICE_TYPE_ALREADY_GET			:number = 3;	// 已兑换过该类型礼包
		public static GIFTCODE_NOTICE_TYPE_SUCCESS			:number = 4;	// 兑换成功
		// _OPRATE_RESULT_H
	}
